config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'

  get 'answers/create'

  devise_for :users
  root "questions#index"
  resources :questions do
    resources :comments
    resources :answers
       
  end
  resources :answers do
    resources :comments    
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
	has_many :comments, as: :commentable
	belongs_to :question
	belongs_to :user

	validates :description, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :questions
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :commentable, polymorphic: true
	belongs_to :user


	validates :content, presence: true
	validates :user_id, presence: true

	before_save :changetext

	def changetext
		self.content.gsub(/WTF/i,"***")
			
	end
	
end

app/models/question.rb
class Question < ApplicationRecord

	DefaultCategoryName = "no category"

	belongs_to :user
	has_many :comments, as: :commentable
	has_many :answers
	belongs_to :category

	validates :title, presence: true, format: { with: /^[a-z0-9 ]+$/i, :multiline => true }
	validates :description, presence: true

	before_save :capitalize


	def capitalize
		if self.title_changed?
			self.title = title.titleize
		end
	end

	def category_name
		# return either category name or "no category"
		category.try(:name) || DefaultCategoryName
		# if category.present?
		# 	category.name
		# else
		# 	"no category"
		# end
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :questions
  has_many :answer
  has_many :comments
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.build(parameters)
    @answer.user_id = current_user.id
    @answer.save
    redirect_to question_path(@question)

    
  end

  def parameters
    params.require(:answer).permit(:description)
    
  end
  def show
    @answer = Answer.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create

    path = request.path
    entity_type = path.match(/\/(\w*)\//)[1].singularize
    klass = entity_type.capitalize.constantize
    klass_id = "#{entity_type}_id"
    @commentable = klass.find(params[klass_id])
    @comment = @commentable.comments.build(parameters)
    # byebug
    # @comment.user_id = current_user.id
    @comment.save
    send "redirect_to_#{entity_type}", @commentable
  end

  def redirect_to_question(commentable)
      redirect_to question_path(commentable)      
  end

  def redirect_to_answer(commentable)
      redirect_to question_answer_path(commentable.question,commentable)
  end

  def parameters
    params[:comment][:user_id] = current_user.id
    params.require(:comment).permit(:content,:user_id)
    
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def new
  	@question = Question.new
    @categories = Category.all
  end

  def show
    @question = Question.find(params[:id])
   # @answer = Answer.find(params[:id])
    
  end


  def create
    user = current_user
    # byebug
    user_id = user.id
  	@question = Question.new(parameters)
    @question.user_id = user_id
    @question.save
  	redirect_to questions_path  	
  end

  def index
  	@questions = Question.all
  end

  def parameters
  	params.require(:question).permit(:title, :description, :category_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/create.html.erb
<h1>Answers#create</h1>
<p>Find me in app/views/answers/create.html.erb</p>

app/views/answers/show.html.erb
<p>
  <strong>Description:</strong>
  <%= @answer.description %>
</p>

<p>
  <%= form_for([@answer, @answer.comments.build]) do |f| %>
    <%= f.label :content %>
    <%= f.text_area :content %>
</p>
<p>
    <%= f.submit %>
  <% end %>

</p>

<h3>Comments</h3>
<p>
  <% @answer.comments.each do |comment| %>
    <p>
      <%= comment.content %>
    </p>
  <% end %>
</p>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Exam</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/questions/create.html.erb
hhwgyhg

app/views/questions/index.html.erb
<p>
  <% @questions.each do |question| %>
  <p>

        <%= question.title %> ----- 
        <%= question.description %>-----
        <%= question.category_name %>
        <%= link_to 'View', question_path(question) %>
  <% end %>
  </p>
</p>
<p>
	<% if user_signed_in? %>
		
		<%= link_to 'Logout', destroy_user_session_path %>		
  		<%= link_to 'Create Question', new_question_path %><br/>
	
	<% else %>
		<%= link_to 'SignUp', new_user_registration_path %> <br/>
		<%= link_to 'LogIn', new_user_session_path %>
	<% end %>
</p>

app/views/questions/new.html.erb
<h3>Please Enter the details</h3>
<p>
	<%= form_for @question do |f| %>
	  <p>
	    <%= f.label :title %><br>
	    <%= f.text_field :title %>
	  </p>
	 
	  <p>
	    <%= f.label :description %><br>
	    <%= f.text_area :description %>
	  </p>

	  <p>
	  	<%= f.label :category_id %><br>
	    <%= f.select :category_id, options_from_collection_for_select(@categories, :id, :name)%>
	  </p>
	 
	  <p>
	    <%= f.submit %>
	  </p>
	<% end %>
</p>

app/views/questions/show.html.erb
<p>
  <strong>Question Title:</strong>
  <%= @question.title %>
</p>

<p>
  <strong>Question Description:</strong>
  <%= @question.description %>
</p>

<p>
  <strong>User id:</strong>
  <%= @question.user_id %>
</p>

<p>
  <strong>Question category:</strong>
  <%= @question.category_name %>
</p>

<h3>Comments</h3>
<p>
  <% @question.comments.each do |comment| %>
    <p>
      <strong>Comments for Question:</strong> 
      <%= comment.content %>
    </p>
  <% end %>
</p>
<%= form_for([@question, @question.comments.build]) do |f| %>
  <p>
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.submit 'Enter' %>
  </p>
<% end %>
<br/>

<h3>Answers</h3>
<p>
  <% @question.answers.each do |answer| %>
    <p>
      <strong>Answers:</strong> 
      <%= answer.description%>
      <%= link_to 'View', question_answer_path(@question, answer) %>
    </p>
  <% end %>
</p>

<%= form_for([@question, @question.answers.build]) do |f| %>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit 'Enter' %>
  </p>

<% end %>

app/views/users/index.html.erb
<p>
	<% if user_signed_in? %>
		
		<%= link_to 'Logout', destroy_user_session_path %>

		
	<% else %>
		<%= link_to 'SignUp', new_user_registration_path %> <br/>
		<%= link_to 'LogIn', new_user_session_path %>
	<% end %>
</p>